image: node0.10
script:
  - npm install
  - make test
services:
  - rgarcia/gearmand
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
